name: Pipeline de Compilação e Testes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Compilação
      run: |
        # Comandos de compilação aqui

    - name: Testes
      run: |
        # Comandos de execução de testes aqui
